name: Deploy API
on:
  push:
    branches: [ main ] # Se d√©clenche quand on pousse sur main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: debian
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/ajpt/ajpt
            git pull origin main
            npm install --omit=dev
            pm2 restart api-jpt || pm2 start index.mjs --name "api-jpt"
            pm2 save